name: Stream To CDN

on:
  workflow_dispatch:

jobs:
  run-ffmpeg:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Process Stream
        run: |
          ffmpeg -y -user_agent "Mozilla/5.0" \
          -i "http://alpha6-tx.me/play/live.php?mac=00:1A:79:7B:8B:39&stream=1917215&extension=m3u8&play_token=61Qz9x1f54" \
          -c copy -hls_time 4 -hls_list_size 5 -f hls playlist.m3u8

      - name: Commit and Push Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u8 *.ts
          git commit -m "Auto-update HLS stream segments" || echo "No changes to commit"
          git push
